import {
  pgTable,
  serial,
  text,
  integer,
  boolean,
  date,
  timestamp,
  jsonb,
  unique,
} from "drizzle-orm/pg-core"

export const expedientes = pgTable("expedientes", {
  id: serial("id").primaryKey(),
  numeroExpediente: text("numero_expediente").notNull(),
  numeroExpedienteNormalizado: text("numero_expediente_normalizado").notNull(),
  solicitante: text("solicitante"),
  solicitanteNormalizado: text("solicitante_normalizado"),
  rut: text("rut"),
  rutNormalizado: text("rut_normalizado"),
  region: text("region"),
  provincia: text("provincia"),
  comuna: text("comuna"),
  comunaNormalizada: text("comuna_normalizada"),
  tipoSolicitud: text("tipo_solicitud"),
  fuenteAgua: text("fuente_agua"),
  caudal: text("caudal"),
  fechaSolicitud: date("fecha_solicitud"),
  fechaAsignacion: date("fecha_asignacion"),
  comentarios: text("comentarios"),
  estado: text("estado").notNull().default("Pendiente de búsqueda"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const publicaciones = pgTable("publicaciones", {
  id: serial("id").primaryKey(),
  fechaPublicacion: date("fecha_publicacion"),
  numeroEdicion: text("numero_edicion"),
  seccion: text("seccion"),
  ministerio: text("ministerio"),
  organismo: text("organismo"),
  categoria: text("categoria"),
  esCandidataDga: boolean("es_candidata_dga").notNull().default(false),
  titulo: text("titulo"),
  materia: text("materia"),
  extracto: text("extracto"),
  region: text("region"),
  provincia: text("provincia"),
  comuna: text("comuna"),
  comunaNormalizada: text("comuna_normalizada"),
  tipoSolicitud: text("tipo_solicitud"),
  fuenteAgua: text("fuente_agua"),
  caudal: text("caudal"),
  coordenadas: text("coordenadas"),
  cve: text("cve").unique(),
  url: text("url"),
  pdfUrl: text("pdf_url"),
  texto: text("texto"),
  numeroResolucion: text("numero_resolucion"),
  fechaResolucion: date("fecha_resolucion"),
  numeroExpedienteDetectado: text("numero_expediente_detectado"),
  rutDetectado: text("rut_detectado"),
  nombreInteresadoDetectado: text("nombre_interesado_detectado"),
  fechaCaptura: timestamp("fecha_captura", { withTimezone: true }).notNull().defaultNow(),
  hashDocumento: text("hash_documento"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
})

export const coincidencias = pgTable(
  "coincidencias",
  {
    id: serial("id").primaryKey(),
    expedienteId: integer("expediente_id").notNull(),
    publicacionId: integer("publicacion_id").notNull(),
    score: integer("score").notNull().default(0),
    coincidenciaExpediente: boolean("coincidencia_expediente").notNull().default(false),
    coincidenciaRut: boolean("coincidencia_rut").notNull().default(false),
    similitudNombre: integer("similitud_nombre").notNull().default(0),
    coincidenciaResolucion: boolean("coincidencia_resolucion").notNull().default(false),
    clasificacion: text("clasificacion").notNull().default("sin_coincidencia"),
    estado: text("estado").notNull().default("pendiente"),
    revisadoPor: text("revisado_por"),
    fechaRevision: timestamp("fecha_revision", { withTimezone: true }),
    motivos: jsonb("motivos"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [unique().on(table.expedienteId, table.publicacionId)],
)

export const ejecucionesScraping = pgTable("ejecuciones_scraping", {
  id: serial("id").primaryKey(),
  fechaInicio: timestamp("fecha_inicio", { withTimezone: true }).notNull().defaultNow(),
  fechaFin: timestamp("fecha_fin", { withTimezone: true }),
  edicion: text("edicion"),
  publicacionesEncontradas: integer("publicaciones_encontradas").notNull().default(0),
  publicacionesNuevas: integer("publicaciones_nuevas").notNull().default(0),
  coincidenciasGeneradas: integer("coincidencias_generadas").notNull().default(0),
  errores: text("errores"),
  /** Fechas del rango consultado que terminaron en ERROR DE CONSULTA (no se pudieron revisar). */
  fechasConError: jsonb("fechas_con_error").$type<string[]>(),
  estado: text("estado").notNull().default("en_progreso"),
})

export const auditoria = pgTable("auditoria", {
  id: serial("id").primaryKey(),
  usuario: text("usuario"),
  fecha: timestamp("fecha", { withTimezone: true }).notNull().defaultNow(),
  accion: text("accion").notNull(),
  expedienteId: integer("expediente_id"),
  publicacionId: integer("publicacion_id"),
  resultadoAnterior: text("resultado_anterior"),
  resultadoNuevo: text("resultado_nuevo"),
})

export const importacionesDga = pgTable("importaciones_dga", {
  id: serial("id").primaryKey(),
  nombreArchivo: text("nombre_archivo").notNull(),
  fecha: timestamp("fecha", { withTimezone: true }).notNull().defaultNow(),
  totalRegistros: integer("total_registros").notNull().default(0),
  registrosDga: integer("registros_dga").notNull().default(0),
  nuevos: integer("nuevos").notNull().default(0),
  actualizados: integer("actualizados").notNull().default(0),
})

/** Un registro por fila del Excel (ID_DOE). Varias filas pueden compartir el mismo CVE. */
export const publicacionesDga = pgTable("publicaciones_dga", {
  id: serial("id").primaryKey(),
  idDoe: text("id_doe").notNull().unique(),
  cve: text("cve"),
  fechaPublicacion: date("fecha_publicacion"),
  cuerpo: integer("cuerpo"),
  titulo: text("titulo"),
  tiposol: text("tiposol"),
  solicitante: text("solicitante"),
  rut: text("rut"),
  rutNormalizado: text("rut_normalizado"),
  region: text("region"),
  provincia: text("provincia"),
  comuna: text("comuna"),
  texto: text("texto"),
  datosOriginales: jsonb("datos_originales").$type<Record<string, unknown>>().notNull(),
  esDga: boolean("es_dga").notNull().default(false),
  tipoProcedimiento: text("tipo_procedimiento"),
  origen: text("origen"),
  reglasAplicadas: jsonb("reglas_aplicadas").$type<string[]>(),
  importacionId: integer("importacion_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

/** Un documento PDF por CVE (deduplicado), compartido por todas las filas con ese CVE. */
export const documentosCve = pgTable("documentos_cve", {
  id: serial("id").primaryKey(),
  cve: text("cve").notNull().unique(),
  fechaPublicacion: date("fecha_publicacion"),
  estado: text("estado").notNull().default("pendiente"),
  urlOrigen: text("url_origen"),
  blobPathname: text("blob_pathname"),
  tamanoBytes: integer("tamano_bytes"),
  fechaDescarga: timestamp("fecha_descarga", { withTimezone: true }),
  intentos: integer("intentos").notNull().default(0),
  ultimoError: text("ultimo_error"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
})

export const reglasDga = pgTable("reglas_dga", {
  id: serial("id").primaryKey(),
  nombre: text("nombre").notNull(),
  campo: text("campo").notNull(),
  patron: text("patron").notNull(),
  efecto: text("efecto").notNull().default("INCLUIR"),
  tipoProcedimiento: text("tipo_procedimiento"),
  origen: text("origen"),
  prioridad: integer("prioridad").notNull().default(100),
  activa: boolean("activa").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
})

export const ejecucionesDescarga = pgTable("ejecuciones_descarga", {
  id: serial("id").primaryKey(),
  fechaInicio: timestamp("fecha_inicio", { withTimezone: true }).notNull().defaultNow(),
  fechaFin: timestamp("fecha_fin", { withTimezone: true }),
  estado: text("estado").notNull().default("en_progreso"),
  total: integer("total").notNull().default(0),
  procesados: integer("procesados").notNull().default(0),
  descargados: integer("descargados").notNull().default(0),
  noDisponibles: integer("no_disponibles").notNull().default(0),
  errores: integer("errores").notNull().default(0),
  mensaje: text("mensaje"),
  actualizadoEn: timestamp("actualizado_en", { withTimezone: true }).notNull().defaultNow(),
})

export const auditoriaDocumentos = pgTable("auditoria_documentos", {
  id: serial("id").primaryKey(),
  fecha: timestamp("fecha", { withTimezone: true }).notNull().defaultNow(),
  accion: text("accion").notNull(),
  cve: text("cve"),
  detalle: text("detalle"),
  usuario: text("usuario"),
})
